export enum AuditActionEnum {
  CREATE_LOAN = 'CREATE_LOAN',
  UPDATE_LOAN = 'UPDATE_LOAN',
  APPROVE_LOAN = 'APPROVE_LOAN',
  REJECT_LOAN = 'REJECT_LOAN',
  ACTIVATE_LOAN = 'ACTIVATE_LOAN',
  REFINANCE_LOAN = 'REFINANCE_LOAN',
  CLOSE_LOAN = 'CLOSE_LOAN',
  APPLY_PENALTY = 'APPLY_PENALTY',
  CREATE_PAYMENT = 'CREATE_PAYMENT',
  CREATE_DISBURSEMENT = 'CREATE_DISBURSEMENT',
  RELEASE_COLLATERAL = 'RELEASE_COLLATERAL',
}
